priority_rules:
  - name: high_priority_hotfix
    priority: 100
    conditions:
      - label = hotfix

queue_rules:
  - name: hotfix
    update_method: rebase
    queue_conditions:
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
      - label = hotfix
    merge_conditions:
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
    merge_method: squash

  - name: default
    update_method: rebase
    queue_conditions:
      - -conflict
      - -draft
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
      - "-title ~= (?i)(wip|draft|🚧)"
    merge_conditions:
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: automatic rebase when behind main
    conditions:
      - -draft
      - -conflict
      - base = main
      - "#check-failure = 0"
      - "#check-pending = 0"
      - "#commits-behind > 0"
    actions:
      rebase: {}

  - name: automatic merge for Kramarich0
    conditions:
      - author = Kramarich0
      - approved-reviews-by = coderabbitai[bot]
      - -draft
      - -conflict
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
      - "-title ~= (?i)(wip|draft|🚧)"
    actions:
      queue:
        name: default
      comment:
        message: "@{{author}}, я мержу этот PR сейчас! 🚀"

  - name: automatic merge for release-please
    conditions:
      - author = doxynix-release-bot[bot]
      - -draft
      - -conflict
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
    actions:
      queue:
        name: default

  - name: automatic merge for dependencies
    conditions:
      - or:
          - author = renovate[bot]
          - author = dependabot[bot]
      - -draft
      - -conflict
      - "#check-pending = 0"
      - "#check-failure = 0"
      - check-success ~= notify
      - "-title ~= (?i)to v([2-9]|[1-9][0-9]+)"
    actions:
      queue:
        name: default
      comment:
        message: "Обновление зависимостей проверено и отправляется в main! 📦"

  # - name: label small PRs // NOTE: возможно пригодится позже
  #   conditions:
  #     - "#files < 5"
  #     - "changes < 50"
  #   actions:
  #     label:
  #       add: ["size:S"]
  # - name: label huge PRs
  #   conditions:
  #     - "changes > 500"
  #   actions:
  #     label:
  #       add: ["size:XL"]
  #     comment:
  #       message: "Ого, @{{author}}, ну ты и настрочил! 🏋️‍♂️ Такой большой PR может проверяться дольше."

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: label on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      label:
        add: ["conflict"]
      comment:
        message: "Упс, @{{author}}, тут конфликт. Поправь руками! 🛠️"
