queue_rules:
  - name: default
    queue_conditions:
      - -conflict
      - -draft
    merge_conditions:
      - or:
        - "check-success ~= ^CI / tests"
        - "check-neutral ~= ^CI / tests"
        - "check-skipped ~= ^CI / tests"
      - or:
        - "check-success ~= ^CI / types"
        - "check-neutral ~= ^CI / types"
        - "check-skipped ~= ^CI / types"
      - or:
        - "check-success ~= ^CI / quality"
        - "check-neutral ~= ^CI / quality"
        - "check-skipped ~= ^CI / quality"
      - or:
        - "check-success ~= ^CI / security"
        - "check-neutral ~= ^CI / security"
        - "check-skipped ~= ^CI / security"
      - or:
        - "check-success ~= GitGuardian Security Checks"
        - "check-neutral ~= GitGuardian Security Checks"
        - "check-skipped ~= GitGuardian Security Checks"
      - or:
        - "check-success ~= ^CodeQL - Code Quality"
        - "check-neutral ~= ^CodeQL - Code Quality"
        - "check-skipped ~= ^CodeQL - Code Quality"
      - or:
        - "check-success ~= ^Vercel"
        - "check-neutral ~= ^Vercel"
        - "check-skipped ~= ^Vercel"
      - or:
        - "check-success ~= ^Trigger\\.dev deployment"
        - "check-neutral ~= ^Trigger\\.dev deployment"
        - "check-skipped ~= ^Trigger\\.dev deployment"
      - or:
        - "check-success ~= ^CI / build"
        - "check-neutral ~= ^CI / build"
        - "check-skipped ~= ^CI / build"
      - or:
        - "check-success ~= ^CI / e2e"
        - "check-neutral ~= ^CI / e2e"
        - "check-skipped ~= ^CI / e2e"
      - or:
        - "check-success ~= ^CI / lighthouse"
        - "check-neutral ~= ^CI / lighthouse"
        - "check-skipped ~= ^CI / lighthouse"
      - or:
        - "check-success ~= ^dependency-review"
        - "check-neutral ~= ^dependency-review"
        - "check-skipped ~= ^dependency-review"

    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: automatic merge for Kramarich0 when CI is green and CodeRabbit approves
    conditions:
      - author = Kramarich0
      - -draft
      - approved-reviews-by = coderabbitai[bot]
      - "#approved-reviews-by >= 1"
      - -conflict

      - or:
        - "check-success ~= ^CI / tests"
        - "check-neutral ~= ^CI / tests"
        - "check-skipped ~= ^CI / tests"
      - or:
        - "check-success ~= ^CI / types"
        - "check-neutral ~= ^CI / types"
        - "check-skipped ~= ^CI / types"
      - or:
        - "check-success ~= ^CI / quality"
        - "check-neutral ~= ^CI / quality"
        - "check-skipped ~= ^CI / quality"
      - or:
        - "check-success ~= ^CI / security"
        - "check-neutral ~= ^CI / security"
        - "check-skipped ~= ^CI / security"
      - or:
        - "check-success ~= GitGuardian Security Checks"
        - "check-neutral ~= GitGuardian Security Checks"
        - "check-skipped ~= GitGuardian Security Checks"
      - or:
        - "check-success ~= ^CodeQL - Code Quality"
        - "check-neutral ~= ^CodeQL - Code Quality"
        - "check-skipped ~= ^CodeQL - Code Quality"
      - or:
        - "check-success ~= ^Vercel"
        - "check-neutral ~= ^Vercel"
        - "check-skipped ~= ^Vercel"
      - or:
        - "check-success ~= ^Trigger\\.dev deployment"
        - "check-neutral ~= ^Trigger\\.dev deployment"
        - "check-skipped ~= ^Trigger\\.dev deployment"
      - or:
        - "check-success ~= ^CI / build"
        - "check-neutral ~= ^CI / build"
        - "check-skipped ~= ^CI / build"
      - or:
        - "check-success ~= ^CI / e2e"
        - "check-neutral ~= ^CI / e2e"
        - "check-skipped ~= ^CI / e2e"
      - or:
        - "check-success ~= ^CI / lighthouse"
        - "check-neutral ~= ^CI / lighthouse"
        - "check-skipped ~= ^CI / lighthouse"
      - or:
        - "check-success ~= ^dependency-review"
        - "check-neutral ~= ^dependency-review"
        - "check-skipped ~= ^dependency-review"
      - or:
        - "check-success ~= ^relative-ci"
        - "check-neutral ~= ^relative-ci"
        - "check-skipped ~= ^relative-ci"
    actions:
      queue:
        name: default

  - name: automatic merge for dependencies updates
    conditions:
      - or:
        - author = renovate[bot]
        - author = dependabot[bot]
      - -draft
      - or:
        - "check-success ~= ^CI / tests"
        - "check-neutral ~= ^CI / tests"
        - "check-skipped ~= ^CI / tests"
      - or:
        - "check-success ~= ^CI / types"
        - "check-neutral ~= ^CI / types"
        - "check-skipped ~= ^CI / types"
      - or:
        - "check-success ~= ^CI / quality"
        - "check-neutral ~= ^CI / quality"
        - "check-skipped ~= ^CI / quality"
      - -conflict
    actions:
      queue:
        name: default

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: label on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      label:
        add:
          - "conflict"
      comment:
        message: "Упс, @{{author}}, тут конфликт. Роботы бессильны, поправь руками! 🛠️"
