sonar.projectKey=doxynix_doxynix
sonar.organization=doxynix

sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/reports/**,**/public/**,**/prisma/migrations/**,**/drizzle/**

sonar.tests=apps/web/src/tests
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.sourceEncoding=UTF-8