import binaryExtensions from "binary-extensions";

import type { FileCategory } from "./discovery.types";

export type ProjectPolicySemanticKind =
  | "api"
  | "backend"
  | "config"
  | "core"
  | "data"
  | "frontend"
  | "infrastructure"
  | "ml"
  | "mobile"
  | "shared"
  | "unknown";

export const PATH_PATTERNS = {
  API: [
    "**/{api,routes,routers,controllers,handlers,graphql,gql,rpc,endpoints}/**",
    "**/*.{controller,handler,router,route,schema,dto,model,trpc,openapi,swagger,gql,graphql,proto,thrift}.*",
  ],
  ASSET: [
    "**/{public,static,assets,css,scss,less,sass,icons,images,fonts,theme,themes,media,videos,audio}/**",
    "**/*.{css,scss,less,sass,svg,png,jpg,jpeg,gif,ico,woff,woff2,ttf,eot,webp,avif,obj,glb}",
  ],
  BENCHMARK: [
    "**/{bench,benchmarks,perf-measures,performance}/**",
    "**/*bench*.{ts,tsx,js,jsx,mts,cts,py,go,rs,java,kt,cs,rb,php}",
    "**/*benchmark*.{ts,tsx,js,jsx,mts,cts,py,go,rs,java,kt,cs,rb,php}",
  ],
  CONFIG: [
    "**/package.json",
    "**/.npmrc",
    "**/.yarnrc*",
    "**/pnpm-workspace.yaml",
    "**/bun.lockb",
    "**/tsconfig*.json",
    "**/jsconfig.json",
    "**/{vite,rollup,next,nuxt,svelte,astro}.config.*",
    "**/biome.json",
    "**/{nginx.conf,Caddyfile,Procfile}",
    "**/{netlify.toml,vercel.json}",
    "**/bunfig.toml",
    "**/deno.json",
    "**/deno.jsonc",
    "**/tsconfig.json",
    "**/tsconfig.*.json",
    "**/CMakeLists.txt",
    "**/meson.build",
    "**/BUILD",
    "**/BUILD.bazel",
    "**/WORKSPACE",
    "**/go.mod",
    "**/go.sum",
    "**/Cargo.lock",
    "**/Cargo.toml",
    "**/pom.xml",
    "**/build.gradle*",
    "**/settings.gradle",
    "**/settings.gradle.kts",
    "**/gradlew",
    "**/gradlew.bat",
    "**/*.csproj",
    "**/*.fsproj",
    "**/*.vbproj",
    "**/*.sln",
    "**/Directory.Build.props",
    "**/Directory.Packages.props",
    "**/composer.json",
    "**/Gemfile",
    "**/pyproject.toml",
    "**/poetry.lock",
    "**/Pipfile",
    "**/Pipfile.lock",
    "**/requirements.txt",
    "**/setup.py",
    "**/setup.cfg",
    "**/mix.exs",
    "**/mix.lock",
    "**/rebar.config",
    "**/rebar.lock",
    "**/docker-compose.{yml,yaml}",
    "**/Dockerfile",
    "**/Makefile",
    "**/app.config",
    "**/web.config",
    "**/*.{prisma,zmodel,proto,thrift,sql}",
    "**/*.{yml,yaml,toml,ini,conf,properties,env,env.example}",
  ],
  DOCS: [
    "**/{docs,doc,documentation,example,examples,sample,samples,guides,website,wiki,manual}/**",
    "**/{README,CHANGELOG,CONTRIBUTING,CODE_OF_CONDUCT,SECURITY,LICENSE,AUTHORS,HISTORY}*",
    "**/*.{md,txt,rst,adoc}",
  ],
  ENTRY: [
    "**/main.{ts,js,py,go,rs,cpp,c,java,kt,cs,rb,php,swift,ex,scala,zig,m,mm}",
    "**/index.{ts,js,py,php}",
    "**/server.{ts,js,py,go}",
    "**/app.{ts,js,py,rb,swift}",
    "**/manage.py",
    "**/wsgi.py",
    "**/asgi.py",
    "**/lambda_function.py",
    "**/__main__.py",
    "**/program.cs",
    "**/startup.cs",
    "**/bootstrap.{php,ts,js}",
    "**/handler.{js,ts,py}",
  ],
  GENERATED: [
    "**/{generated,.generated,dist,build,out,target,bin,obj,vendor,node_modules,.next,.nuxt,.svelte-kit,.output,.turbo,.cache,.parcel-cache}/**",
    "**/__generated__/**",
  ],
  IGNORE: [
    "**/{.git,node_modules,dist,build,out,target,.next,.nuxt,.svelte-kit,.output,vendor,bower_components,coverage,.pnpm-store,.yarn,.turbo,.parcel-cache,.cache,.serverless,.terraform,.gradle,.mvn,.dart_tool,__pycache__,.pytest_cache,.mypy_cache,.ruff_cache,.tox,.nox,.venv,venv,obj,Debug,Release}/**",
    "**/{.ds_store,thumbs.db,.idea,.vscode}/**",
    `**/*.{${binaryExtensions.join(",")}}`,
    "**/*.{pdf,doc,docx,xls,xlsx,ppt,pptx,zip,tar,gz,7z,rar,mp3,mp4,wav,exe,dll,so,pyc}",
  ],
  INFRA: [
    "**/.github/workflows/**",
    "**/{deploy,deployment,helm,k8s,terraform,infra,infrastructure}/**",
    "**/docker-compose.{yml,yaml}",
    "**/.gitlab-ci.yml",
    "**/azure-pipelines.yml",
    "**/Jenkinsfile",
    "**/{cloudformation,pulumi}/**",
    "**/*.{tfvars,nomad,hcl}",
    "**/Dockerfile",
    "**/*.tf",
  ],
  INFRA_DIRS: [
    "**/cmd/**",
    "**/bin/**",
    "**/pages/api/**",
    "**/app/api/**",
    "**/functions/**",
    "**/k8s/**",
  ],
  ML: [
    "**/{models,notebooks,data_science,training,datasets,inference}/**",
    "**/*.{ipynb,onnx,pb,h5,pt,pth,pkl,joblib,dvc}",
  ],
  MOBILE: [
    "**/{ios,android,mobile,cordova,capacitor,flutter,react-native}/**",
    "**/*.{swift,plist,xcworkspace,xcodeproj,storyboard,xib}",
  ],
  OPENAPI: [
    "**/openapi.{json,yaml,yml}",
    "**/swagger.{json,yaml,yml}",
    "**/*openapi*",
    "**/*swagger*",
  ],
  RUNTIME_SOURCE: [
    "**/{src,app,lib,core,domain,internal,pkg,services,server,include,crates,packages,modules,cmd,cli,sdk,entities,features,widgets}/**",
    "**/*.{service,repository,use-case,handler,router,route,controller,model,entity,dto,contract,action,util,helper,logic}.*",
  ],
  SENSITIVE: [
    "**/.env*",
    "**/*.{keystore,jks}",
    "**/config/master.key",
    "**/credentials.json",
    "**/{secrets,secret,credentials,auth,keys}/**",
    "**/*.{pem,key,p12,pfx,crt,der}",
  ],
  TEST: [
    "**/{test,tests,spec,__tests__,__mocks__,fixture,fixtures,e2e}/**",
    "**/runtime-tests/**",
    "**/*.{test,spec,cy,steps}.*",
  ],
  TOOLING: [
    "**/{scripts,cli,tools}/**",
    "**/{eslint,prettier,vitest,playwright,jest,stryker,typedoc,webpack,vite,rollup,postcss}.config.*",
    "**/*.config.{js,ts,mjs,cjs}",
  ],
} as const;

export const PROJECT_POLICY_RULES = {
  categoryPolicy: {
    nonArchitectureCategories: new Set<FileCategory>([
      "asset",
      "benchmark",
      "docs",
      "generated",
      "test",
    ]),
    secondaryEvidenceCategories: new Set<FileCategory>([
      "asset",
      "benchmark",
      "config",
      "docs",
      "generated",
      "infra",
      "test",
      "tooling",
    ]),
  },
  fileHints: {
    dependencyLockfiles: [
      "package-lock.json",
      "pnpm-lock.yaml",
      "yarn.lock",
      "bun.lock",
      "bun.lockb",
      "go.sum",
      "cargo.lock",
      "poetry.lock",
      "pipfile.lock",
      "mix.lock",
      "rebar.lock",
      "composer.lock",
      "gradle.lockfile",
      ".terraform.lock.hcl",
    ],
    lowSignalConfigNames: ["gradlew", "gradlew.bat"],
    polyglotConfigHints: [
      "build.gradle",
      "build.gradle.kts",
      "cmakelists.txt",
      "cargo.toml",
      "deno.json",
      "deno.jsonc",
      "directory.build.props",
      "directory.packages.props",
      "dockerfile",
      "gemfile",
      "go.mod",
      "makefile",
      "meson.build",
      "mix.exs",
      "package.json",
      "pipfile",
      "pipfile.lock",
      "poetry.lock",
      "pom.xml",
      "pyproject.toml",
      "rebar.config",
      "requirements.txt",
      "settings.gradle",
      "settings.gradle.kts",
      "setup.cfg",
      "setup.py",
    ],
  },

  grouping: {
    genericGroupRoots: new Set([
      "app",
      "apps",
      "backend",
      "cli",
      "client",
      "cmd",
      "components",
      "core",
      "crates",
      "domain",
      "frontend",
      "include",
      "internal",
      "lib",
      "libs",
      "mobile",
      "modules",
      "packages",
      "pages",
      "pkg",
      "sdk",
      "server",
      "services",
      "shared",
      "src",
      "workers",
    ]),
    groupingRoots: new Set([
      "app",
      "apps",
      "backend",
      "cli",
      "client",
      "cmd",
      "components",
      "core",
      "crates",
      "desktop",
      "domain",
      "entities",
      "extensions",
      "features",
      "frontend",
      "include",
      "internal",
      "lib",
      "libs",
      "mobile",
      "modules",
      "packages",
      "pages",
      "pkg",
      "plugins",
      "sdk",
      "server",
      "services",
      "shared",
      "src",
      "widgets",
      "workers",
    ]),
    jvmSourceRoots: new Set(["clojure", "groovy", "java", "kotlin", "resources", "scala"]),
  },
  manifests: {
    rootFiles: [
      "cargo.toml",
      "go.mod",
      "package.json",
      "pom.xml",
      "pyproject.toml",
      "readme.md",
      "requirements.txt",
      "setup.py",
      "tsconfig.json",
    ],
  },
  security: {
    patterns:
      /eval\(|exec\(|dangerouslysetinnerhtml|innerhtml\s*=|password|secret|api[_-]?key|token|bearer|auth|credentials|private_key/i,
    todoPatterns: /\/\/\s*todo|\/\/\s*fixme|\/\/\s*xxx|\/\/\s*hack/i,
  },
  semanticPrefixes: {
    backend: ["src/server/"],
    frontend: ["src/app/"],
    shared: ["src/shared/"],
  },
  semantics: {
    apiSegments: [
      "api",
      "router",
      "routers",
      "route",
      "routes",
      "controller",
      "controllers",
      "handler",
      "handlers",
      "trpc",
      "grpc",
      "rpc",
      "gateway",
      "endpoint",
      "endpoints",
    ],
    backendSegments: [
      "server",
      "backend",
      "services",
      "workers",
      "jobs",
      "cli",
      "cmd",
      "internal",
      "daemon",
      "command",
      "commands",
      "processor",
      "processors",
      "consumer",
      "consumers",
    ],
    configSegments: ["config", "configs"],
    coreSegments: ["engine", "core", "domain", "runtime", "kernel"],
    dataSegments: [
      "prisma",
      "migrations",
      "schema",
      "schemas",
      "db",
      "database",
      "repositories",
      "repository",
      "persistence",
      "storage",
      "store",
      "dao",
      "orm",
      "redis",
      "mongo",
      "postgres",
      "mysql",
      "sqlite",
    ],
    frontendSegments: [
      "app",
      "pages",
      "components",
      "features",
      "widgets",
      "frontend",
      "client",
      "ui",
      "screens",
      "views",
      "templates",
      "android",
      "ios",
    ],
    infrastructureSegments: [
      "infra",
      "infrastructure",
      "adapters",
      "drivers",
      "integrations",
      "deploy",
      "helm",
      "terraform",
      "ansible",
      "k8s",
      "kubernetes",
      "cloud",
      "providers",
    ],
    sharedSegments: ["shared", "common", "utils", "helpers", "sdk", "kernel", "base"],
  },
} as const;
