import { IGNORE_PATTERNS } from "@/server/core/git/ignore-rules";

/**
 * How source paths look. Kept in core because the GitHub transport needs the same
 * path policy as the analysis engine: which files are ignored, sensitive, or too
 * low-signal to read. Nothing here knows about any particular analysis metric.
 */
export const PATH_PATTERNS = {
  API: [
    "**/{api,routes,routers,controllers,handlers,graphql,gql,rpc,endpoints}/**",
    "**/*.{controller,handler,router,route,schema,dto,model,trpc,openapi,swagger,gql,graphql,proto,thrift}.*",
  ],
  ASSET: [
    "**/{public,static,assets,css,scss,less,sass,icons,images,fonts,theme,themes,media,videos,audio}/**",
    "**/*.{css,scss,less,sass,svg,png,jpg,jpeg,gif,ico,woff,woff2,ttf,eot,webp,avif,obj,glb}",
  ],
  BENCHMARK: [
    "**/{bench,benchmarks,perf-measures,performance}/**",
    "**/*bench*.{ts,tsx,js,jsx,mts,cts,py,go,rs,java,kt,cs,rb,php}",
    "**/*benchmark*.{ts,tsx,js,jsx,mts,cts,py,go,rs,java,kt,cs,rb,php}",
  ],
  CONFIG: [
    "**/package.json",
    "**/.npmrc",
    "**/.yarnrc*",
    "**/pnpm-workspace.yaml",
    "**/pnpm-lock.yaml",
    "**/bun.lock",
    "**/bun.lockb",
    "**/deno.lock",
    "**/tsconfig*.json",
    "**/jsconfig.json",
    "**/{vite,rollup,next,nuxt,svelte,astro,tsup,rspack,farm,rolldown}.config.*",
    "**/biome.json",
    "**/{nginx.conf,Caddyfile,Procfile}",
    "**/{netlify.toml,vercel.json}",
    "**/bunfig.toml",
    "**/deno.json",
    "**/deno.jsonc",
    "**/tsconfig.json",
    "**/tsconfig.*.json",
    "**/CMakeLists.txt",
    "**/meson.build",
    "**/BUILD",
    "**/BUILD.bazel",
    "**/WORKSPACE",
    "**/go.mod",
    "**/go.sum",
    "**/Cargo.lock",
    "**/Cargo.toml",
    "**/pom.xml",
    "**/build.gradle*",
    "**/settings.gradle",
    "**/settings.gradle.kts",
    "**/gradlew",
    "**/gradlew.bat",
    "**/*.csproj",
    "**/*.fsproj",
    "**/*.vbproj",
    "**/*.sln",
    "**/Directory.Build.props",
    "**/Directory.Packages.props",
    "**/composer.json",
    "**/Gemfile",
    "**/pyproject.toml",
    "**/poetry.lock",
    "**/Pipfile",
    "**/Pipfile.lock",
    "**/requirements.txt",
    "**/setup.py",
    "**/setup.cfg",
    "**/mix.exs",
    "**/mix.lock",
    "**/rebar.config",
    "**/rebar.lock",
    "**/docker-compose.{yml,yaml}",
    "**/Dockerfile",
    "**/Makefile",
    "**/app.config",
    "**/web.config",
    "**/*.{prisma,zmodel,proto,thrift,sql}",
    "**/*.{yml,yaml,toml,ini,conf,properties,env,env.local,env.production,env.example}",
  ],
  DOCS: [
    "**/{docs,doc,documentation,examples,samples,guides,website,wiki,manual}/**",
    "**/example/**",
    "**/sample/**",
    "**/{README,CHANGELOG,CONTRIBUTING,CODE_OF_CONDUCT,SECURITY,LICENSE,AUTHORS,HISTORY}*",
    "**/*.{md,txt,rst,adoc}",
  ],
  ENTRY: [
    "**/main.{ts,js,py,go,rs,cpp,c,java,kt,cs,rb,php,swift,ex,scala,zig,m,mm}",
    "**/index.{ts,js,py,php}",
    "**/server.{ts,js,py,go}",
    "**/app.{ts,js,py,rb,swift}",
    "**/manage.py",
    "**/wsgi.py",
    "**/asgi.py",
    "**/lambda_function.py",
    "**/__main__.py",
    "**/program.cs",
    "**/startup.cs",
    "**/bootstrap.{php,ts,js}",
    "**/handler.{js,ts,py}",
  ],
  GENERATED: [
    "**/{generated,.generated,dist,build,out,target,bin,obj,vendor,node_modules,.next,.nuxt,.svelte-kit,.astro,.nitro,.wrangler,.output,.turbo,.cache,.parcel-cache}/**",
    "**/__generated__/**",
  ],
  IGNORE: IGNORE_PATTERNS,
  INFRA: [
    "**/.github/workflows/**",
    "**/{deploy,deployment,helm,k8s,terraform,infra,infrastructure}/**",
    "**/docker-compose.{yml,yaml}",
    "**/.gitlab-ci.yml",
    "**/azure-pipelines.yml",
    "**/Jenkinsfile",
    "**/{cloudformation,pulumi}/**",
    "**/*.{tfvars,nomad,hcl}",
    "**/Dockerfile",
    "**/*.tf",
  ],
  INFRA_DIRS: [
    "**/cmd/**",
    "**/bin/**",
    "**/pages/api/**",
    "**/app/api/**",
    "**/functions/**",
    "**/k8s/**",
  ],
  ML: [
    "**/{models,notebooks,data_science,training,datasets,inference}/**",
    "**/*.{ipynb,onnx,pb,h5,pt,pth,pkl,joblib,dvc}",
  ],
  MOBILE: [
    "**/{ios,android,mobile,cordova,capacitor,flutter,react-native}/**",
    "**/*.{swift,plist,xcworkspace,xcodeproj,storyboard,xib}",
  ],
  OPENAPI: [
    "**/openapi.{json,yaml,yml}",
    "**/swagger.{json,yaml,yml}",
    "**/*openapi*",
    "**/*swagger*",
  ],
  RUNTIME_SOURCE: [
    "**/{src,app,lib,core,domain,internal,pkg,services,server,include,crates,packages,modules,cmd,cli,sdk,entities,features,widgets}/**",
    "**/*.{service,repository,use-case,handler,router,route,controller,model,entity,dto,contract,action,util,helper,logic}.*",
  ],
  SENSITIVE: [
    "**/.env*",
    "**/*.{keystore,jks}",
    "**/config/master.key",
    "**/credentials.json",
    "**/{secrets,secret,credentials,keys}/**",
    "**/*.{pem,key,p12,pfx,crt,der}",
  ],
  TEST: [
    "**/{test,tests,spec,__tests__,__mocks__,fixture,fixtures,e2e}/**",
    "**/runtime-tests/**",
    "**/*.{test,spec,cy,steps}.*",
  ],
  TOOLING: [
    "**/{scripts,cli,tools}/**",
    "**/{eslint,prettier,vitest,playwright,jest,stryker,typedoc,webpack,vite,rollup,postcss}.config.*",
    "**/*.config.{js,ts,mjs,cjs}",
  ],
} as const;

export const dependencyLockfiles = [
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lock",
  "bun.lockb",
  "deno.lock",
  "go.sum",
  "cargo.lock",
  "poetry.lock",
  "pipfile.lock",
  "mix.lock",
  "rebar.lock",
  "composer.lock",
  "gradle.lockfile",
  ".terraform.lock.hcl",
];

export const lowSignalConfigNames = ["gradlew", "gradlew.bat"];

export const frontendDirectories = [
  "ui",
  "components",
  "views",
  "screens",
  "containers",
  "layouts",
  "widgets",
];
