// Files that must never be edited by hand (AGENTS.md). The hook denies the
// edit and points at the correct workflow instead of failing silently.
const GENERATED_FILES: Array<{ path: string; hint: string }> = [
  {
    hint: "schema.prisma is generated by ZenStack — edit prisma/models/*.zmodel instead (skill: zenstack-migration).",
    path: "apps/web/prisma/schema.prisma",
  },
  {
    hint: "routeTree.gen.ts is generated by the TanStack Router plugin — edit files in src/routes/ instead.",
    path: "apps/siem-client/src/routeTree.gen.ts",
  },
];

const FORBIDDEN_PACKAGE_MANAGERS = ["npm", "yarn", "pnpm", "npx"];

const RM_REASON =
  "Recursive delete is forbidden — remove files with the edit tool instead, or delete a single file with `rm <file>` (no flags). See AGENTS.md.";

function rmHit(tokens: readonly string[]): boolean {
  const argv = tokens.filter((t) => t !== "sudo");
  if (argv[0] !== "rm") return false;
  return argv
    .slice(1)
    .filter((t) => t.startsWith("-") && t !== "--")
    .some((flag) => flag === "--recursive" || /[rR]/.test(flag.replace(/^--no-/, "")));
}

const PUSH_REASON =
  "Force-push is forbidden — rewrite history locally (git rebase / git branch -m) and push normally. See linear-git-workflow skill.";

function forcePushHit(tokens: readonly string[]): boolean {
  const args = tokens.filter((t) => t !== "sudo");
  if (args[0] !== "git" || args[1] !== "push") return false;
  return args.slice(2).some((t) => t === "-f" || t.startsWith("--force"));
}

function normalized(path: string): string {
  return path.replace(/\\/g, "/");
}

function generatedHit(resources: readonly string[]): string | null {
  for (const raw of resources) {
    const file = normalized(raw);
    const hit = GENERATED_FILES.find((g) => file === g.path || file.endsWith(`/${g.path}`));
    if (hit != null) return `Do not edit ${hit.path} by hand. ${hit.hint}`;
  }
  return null;
}

function shellSegments(command: string): string[] {
  return command
    .split(/&&|\|\||[;|]/)
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
}

function tokenize(segment: string): string[] {
  return (segment.match(/"[^"]*"|'[^']*'|\S+/g) ?? []).map((t) =>
    t.startsWith('"') || t.startsWith("'") ? t.slice(1, -1) : t,
  );
}

function shellHit(command: string): string | null {
  for (const segment of shellSegments(command)) {
    const tokens = tokenize(segment);
    const binary = (tokens[0] === "sudo" ? tokens[1] : tokens[0])?.split("/").pop() ?? "";
    if (FORBIDDEN_PACKAGE_MANAGERS.includes(binary)) {
      return `Package manager "${binary}" is forbidden — Bun only (bun install, bun run, bun x). See AGENTS.md §1.`;
    }
    if (rmHit(tokens)) return RM_REASON;
    if (forcePushHit(tokens)) return PUSH_REASON;
    if (tokens.includes("--no-verify") && (binary === "git" || binary === "bun")) {
      return "Skipping lefthook gates with --no-verify is forbidden — fix the underlying error instead (Biome, arch:check, cspell, secretlint must pass).";
    }
  }
  return null;
}

type PermissionEvent = {
  action: string;
  resources: readonly string[];
  effect: string;
  message?: string;
};

type PluginContext = {
  permission: { hook: (name: string, cb: (event: PermissionEvent) => void) => Promise<unknown> };
};

export default {
  id: "monorepo-laws",
  async setup(ctx: PluginContext) {
    await ctx.permission.hook("evaluate", (event) => {
      if (event.action === "edit" || event.action === "write" || event.action === "patch") {
        const reason = generatedHit(event.resources);
        if (reason != null) {
          event.effect = "deny";
          event.message = reason;
        }
        return;
      }
      if (event.action === "shell") {
        for (const resource of event.resources) {
          const reason = shellHit(resource);
          if (reason != null) {
            event.effect = "deny";
            event.message = reason;
            return;
          }
        }
      }
    });
  },
};
