name: "Close stale pull requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@db5d06a4c82d5e94513c09c406638111df61f63e
        with:
          stale-pr-message: 'This PR has not been updated for 30 days. It will be closed in 7 days if no new activity occurs.'
          close-pr-message: 'This PR was closed due to inactivity.'
          days-before-stale: 30
          days-before-close: 7
